# Generated by Django 5.2.6 on 2025-10-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cradits_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='credits_available',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
