# Generated by Django 5.2.6 on 2025-09-30 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default=uuid.UUID('a78812c1-16a8-47ee-98a9-b6dc3d1efd4f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
