# Generated by Django 5.2.6 on 2025-10-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_cradits_used_user_credits_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cradits_used',
            new_name='credits_used',
        ),
    ]
