# Generated by Django 5.2.6 on 2025-10-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_created_at_remove_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpage',
            name='page_picture_url',
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
