# Generated by Django 5.2.6 on 2025-10-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_facebookpage_page_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
