# Generated by Django 5.2.6 on 2025-10-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_facebookpage_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpage',
            name='business_context',
        ),
    ]
