# Generated by Django 5.2.6 on 2025-10-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Base instructions for AI behavior', null=True),
        ),
    ]
