# Generated by Django 5.2.6 on 2025-10-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_credits_available_user_credits_user_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='system_prompt',
            field=models.TextField(default='', help_text='Base instructions for AI behavior'),
        ),
    ]
