# Generated by Django 5.2.6 on 2025-10-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_otp_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='otp',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
