# Generated by Django 5.2.6 on 2025-10-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_otp_options_alter_otp_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
