# Generated by Django 5.2.6 on 2025-10-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_otp_user_delete_attempt_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='primary',
            field=models.BooleanField(default=True),
        ),
    ]
