# Generated by Django 5.2.6 on 2025-10-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='business_context',
            field=models.TextField(default='', help_text='Extra knowledge about your business or product for ai'),
        ),
    ]
