# Generated by Django 5.2.6 on 2025-10-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_facebookpage_business_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopping_cost',
            field=models.IntegerField(default=0),
        ),
    ]
