# Generated by Django 5.2.6 on 2025-10-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_shopping_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shopping_cost',
            new_name='shipping_cost',
        ),
    ]
