# Generated by Django 5.2.7 on 2025-11-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_shopping_cost_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='comment_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
