# Generated by Django 5.2.7 on 2025-11-12 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_facebookpage_comment_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_url', models.CharField(max_length=255)),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('connected', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facebook_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woo', to='core.facebookpage')),
            ],
        ),
    ]
