# Generated by Django 5.2.7 on 2025-11-12 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_wooconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wooconnection',
            name='facebook_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='woo', to='core.facebookpage'),
        ),
    ]
