# Generated by Django 5.2.7 on 2025-11-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_notification_facebookpage_notification_action_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, default='#', max_length=255, null=True),
        ),
    ]
