# Generated by Django 5.2.7 on 2025-11-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='product_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
