# Generated by Django 5.2.6 on 2025-09-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sender_id', models.CharField(max_length=100)),
                ('recipient_id', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('content', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
