# Generated by Django 5.2.6 on 2025-10-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='credits_used',
            field=models.IntegerField(default=0),
        ),
    ]
