# Generated by Django 5.2.6 on 2025-10-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='input_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='output_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
