# Generated by Django 5.2.6 on 2025-10-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_credits_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['updated_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
    ]
