# Generated by Django 5.2.6 on 2025-10-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_conversation_input_tokens_conversation_output_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
