# Generated by Django 5.2.6 on 2025-10-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_conversation_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
