# Generated by Django 5.2.6 on 2025-10-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_conversation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
