# Generated by Django 5.2.6 on 2025-09-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_conversation_remove_message_recipient_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('page_id', 'user_id')},
        ),
    ]
