# Generated by Django 5.2.7 on 2025-11-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_conversation_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
