# Generated by Django 5.2.6 on 2025-10-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_conversation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
